global using Microsoft.Extensions.Logging;
global using Moq;
global using ToDoList.Application.Dtos;
global using ToDoList.Application.Services;
global using ToDoList.Application.Services.Interfaces;
global using ToDoList.Domain.Entities;
global using ToDoList.Domain.Interfaces;
global using ToDoList.Endpoints;
global using ToDoList.Utilities;
